### PR TITLE
Update for Elixir v1.6

### PR DESCRIPTION
**Pull request by bryanenders**
Why
---

* Elixir v1.6 had major implications for the style guide
* The code was slightly outdated

How
---

* Set updated Elixir and Erlang versions
* Update style guide
* Run `mix format` against codebase

### CODE REVIEW

**Review by danielspofford — COMMENTED** [review]
Everything LGTM except it looks like CircleCI is hanging when attempting to `asdf install`, perhaps due to caching that directory in the circle.yml?

**Review by squaresurf — COMMENTED** [review]
It'd probably be a good idea to mention `mix format` in the style guide as well as add documentation regarding setting up CircleCI to enforce the usage of the formatter.

**Comment by endersstocker** [comment]
It appears to be [an issue in kerl](https://github.com/kerl/kerl/issues/245), which has been fixed for the next release. This may be blocked until the kerl patch is released and asdf updates to the patched kerl.

One option would be to remove the `.tool-versions` update and create an issue to update it (once asdf is updated). Thoughts?

**Comment by endersstocker** [comment]
We probably ought to upgrade to CircleCI 2. It has official Elixir support.

**Comment by squaresurf** [comment]
I agree. I started looking into that last night. @Gringill has seemed to have some success in that avenue.

**Review by samcdavid — APPROVED** [review]

**Comment by bryanenders** [comment]
>It'd probably be a good idea to mention mix format in the style guide as well as add documentation regarding setting up CircleCI to enforce the usage of the formatter.

@squaresurf That’s a great idea. If you want to make an issue for this, that would be helpful. I went ahead and merged this PR so that the style guide wouldn't mislead.

**Comment by squaresurf** [comment]
@endersstocker I've created #52 :smile:

**Pull request merged**
